# Generated by Django 4.2.30 on 2026-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegadget',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gadgets/'),
        ),
    ]
